*&---------------------------------------------------------------------*
*&  Include           ZDC_PERS_SELECTION
*&---------------------------------------------------------------------*

"--- Personal Info Selection Block ---
SELECTION-SCREEN COMMENT /1(54) t_blank5.
SELECTION-SCREEN BEGIN OF BLOCK ID WITH FRAME TITLE TEXT-001.
SELECTION-SCREEN COMMENT /1(54) t_blank.
SELECTION-SCREEN COMMENT /1(75) TEXT-C02.
SELECTION-SCREEN COMMENT /1(54) t_blank2.
PARAMETERS: p_pID TYPE ZDC_PSID_DE OBLIGATORY.
SELECTION-SCREEN COMMENT /1(54) t_blank3.
SELECTION-SCREEN END OF BLOCK ID.


"--- Basic Info ---
SELECTION-SCREEN BEGIN OF BLOCK GR1 WITH FRAME.
SELECTION-SCREEN COMMENT /1(75) TEXT-C01.
SELECTION-SCREEN COMMENT /1(54) t_blank4.
PARAMETERS: p_pname  TYPE ZDC_PNAME_DE,
            p_psname TYPE ZDC_PSNAME_DE,
            p_bday   TYPE dats,
            p_gender TYPE char1 NO-DISPLAY,
            p_pnmbr  TYPE CHAR20,
            p_email  TYPE zdc_pstring40_de.

DATA(lv_cleaned) = p_pnmbr.
CONDENSE lv_cleaned NO-GAPS.


"--- Gender Radio Buttons ---
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(15) TEXT-G01.
PARAMETERS: r_male RADIOBUTTON GROUP gen DEFAULT 'X'.
SELECTION-SCREEN COMMENT 19(6) TEXT-T01.
PARAMETERS: r_female RADIOBUTTON GROUP gen.
SELECTION-SCREEN COMMENT 28(6) TEXT-T02.
SELECTION-SCREEN END OF LINE.


"--- Marital Status ---
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(15) TEXT-G02.
PARAMETERS: r_single RADIOBUTTON GROUP mar DEFAULT 'X'.
SELECTION-SCREEN COMMENT 19(6) TEXT-T03.
PARAMETERS: r_marrd RADIOBUTTON GROUP mar.
SELECTION-SCREEN COMMENT 28(7) TEXT-T04.
PARAMETERS: r_div RADIOBUTTON GROUP mar.
SELECTION-SCREEN COMMENT 38(8) TEXT-T05.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK GR1.


"--- Address Block ---
SELECTION-SCREEN BEGIN OF BLOCK GR2 WITH FRAME TITLE TEXT-004 NO INTERVALS.
PARAMETERS: p_nation TYPE char40 DEFAULT TEXT-N01,
            p_adrs   TYPE ZDC_PADRESS_DE,
            p_adrs2  TYPE ZDC_PADRESS2_DE,
            p_city   TYPE char30,
            p_cntry  TYPE CHAR3.
SELECTION-SCREEN END OF BLOCK GR2.


"--- Employment & Notes Block ---
SELECTION-SCREEN BEGIN OF BLOCK GR3 WITH FRAME TITLE TEXT-005 NO INTERVALS.
PARAMETERS: p_estts TYPE char30 AS LISTBOX VISIBLE LENGTH 30,
            p_notes TYPE zdc_pstring200_de.
SELECTION-SCREEN END OF BLOCK GR3.
